name: Deploy to Org

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install Salesforce CLI
        run: |
          npm install -g @salesforce/cli
      
      - name: Authorize Salesforce Org
        run: |
          echo "y" | sf org login \
            --username "${{ secrets.SF_USERNAME }}" \
            --instance-url "${{ secrets.SF_LOGIN_URL }}" \
            --alias PortfolioOrg \
            --set-default
        env:
          SF_PASSWORD: ${{ secrets.SF_PASSWORD }}
        
      - name: Deploy to Org
        run: |
          sf project deploy start --source-dir force-app --target-org PortfolioOrg